
auth0url=https\://dev-nn-extid.eu.auth0.com
authToken=/oauth/token
baseurl=https\://sogrow-app-dev-weu.azurewebsites.net
features=src/test/resources/features
payloads=src/main/resources/payloads
stepDefinition=src/main/java/stepDefinition
swaggerUrl=https\://sogrow-app-dev-weu.azurewebsites.net/swagger/v2/swagger.json
